#!/usr/bin/env python3
"""
Generates synthetic sample data for this dashboard. All data is fabricated.

Outputs (same schema the dashboard pages consume):
  data/data.js        window.DATA_VERSION, window.DATA_META, window.DATA_AGG,
                      window.DATA_MAP_INDEX
  data/map/<sa>.js    window.DATA_MAP_CHUNKS["<Service Area>"] = [ ...points ]

Deterministic: seeded RNG, so re-running produces identical files.

Run:  python3 generate_sample_data.py
"""

import json
import math
import pathlib
import random

rng = random.Random(42)

HERE = pathlib.Path(__file__).resolve().parent
DATA_DIR = HERE / "data"
MAP_DIR = DATA_DIR / "map"

HEADER = "// SYNTHETIC SAMPLE DATA - generated by generate_sample_data.py. No real records.\n"

YEARS = [2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]
PARTIAL_YEARS = {"2026": "APR"}  # 2026 only has billing data through April

# Wastewater treatment plant service areas (public infrastructure names)
# mapped to their map-chunk file slug.
SERVICE_AREAS = {
    "69th Street": "69th-street",
    "Almeda Sims": "almeda-sims",
    "Beltway": "beltway",
    "Blackhawk": "blackhawk",
    "Cedar Bayou": "cedar-bayou",
    "Chelford City": "chelford-city",
    "Chocolate Bayou": "chocolate-bayou",
    "Clinton Park": "clinton-park",
    "Easthaven": "easthaven",
    "FWSD #23": "fwsd-23",
    "Forest Cove": "forest-cove",
    "Greenridge": "greenridge",
    "HCMUD 400": "hcmud-400",
    "Homestead": "homestead",
    "Imperial Valley": "imperial-valley",
    "Intercontinental": "intercontinental",
    "Keegans Bayou": "keegans-bayou",
    "Kingwood": "kingwood",
    "MC MUD #48": "mc-mud-48",
    "MUD #203": "mud-203",
    "Metro Central": "metro-central",
    "Northbelt": "northbelt",
    "Northeast": "northeast",
    "Northgate": "northgate",
    "Northwest": "northwest",
    "Park Ten": "park-ten",
    "Sagemont": "sagemont",
    "Sims Bayou": "sims-bayou",
    "Southeast": "southeast",
    "Southwest": "southwest",
    "Tidwell Timbers": "tidwell-timbers",
    "Turkey Creek": "turkey-creek",
    "Upper Brays": "upper-brays",
    "WCID #111": "wcid-111",
    "WCID #47": "wcid-47",
    "WCID #76": "wcid-76",
    "West District": "west-district",
    "West Lake Houston": "west-lake-houston",
    "Westway": "westway",
    "White Oak": "white-oak",
    "Willowbrook": "willowbrook",
}

# Synthetic meter-basin prefix per service area (unique, fabricated codes).
BASIN_PREFIX = {
    "69th Street": "SS", "Almeda Sims": "AL", "Beltway": "BW", "Blackhawk": "BH",
    "Cedar Bayou": "CE", "Chelford City": "CH", "Chocolate Bayou": "CB",
    "Clinton Park": "CP", "Easthaven": "EH", "FWSD #23": "FW", "Forest Cove": "FC",
    "Greenridge": "GR", "HCMUD 400": "HM", "Homestead": "HS",
    "Imperial Valley": "IV", "Intercontinental": "IC", "Keegans Bayou": "KB",
    "Kingwood": "KW", "MC MUD #48": "MC", "MUD #203": "MD", "Metro Central": "MT",
    "Northbelt": "NB", "Northeast": "NE", "Northgate": "NG", "Northwest": "NW",
    "Park Ten": "PT", "Sagemont": "SG", "Sims Bayou": "SB", "Southeast": "SE",
    "Southwest": "SW", "Tidwell Timbers": "TT", "Turkey Creek": "TK",
    "Upper Brays": "UB", "WCID #111": "WA", "WCID #47": "WI", "WCID #76": "WQ",
    "West District": "WD", "West Lake Houston": "WL", "Westway": "WY",
    "White Oak": "WO", "Willowbrook": "WB",
}

# Account class -> (share of accounts, mean gallons/day per account,
#                   probability the class exists in a given meter basin)
CLASSES = {
    "RES":        (0.780, 210,   1.00),
    "COMM":       (0.090, 1400,  0.90),
    "MULTIF":     (0.045, 2600,  0.75),
    "IRRIG":      (0.030, 900,   0.70),
    "GOV":        (0.020, 1800,  0.55),
    "FIRE":       (0.008, 15,    0.25),
    "SEWER":      (0.007, 300,   0.25),
    "CW-MUD":     (0.004, 45000, 0.05),
    "EBS":        (0.003, 600,   0.05),
    "ECC":        (0.002, 500,   0.05),
    "DRNONLY":    (0.002, 5,     0.05),
    "TRANSIENT":  (0.002, 350,   0.05),
    "RESALE":     (0.002, 60000, 0.05),
    "CW-INDIR":   (0.001, 30000, 0.05),
    "CW-WELL":    (0.001, 12000, 0.05),
    "CW-WAU":     (0.001, 25000, 0.05),
    "INDSWRSUR":  (0.001, 20000, 0.05),
    "CW-RECLAIM": (0.0005, 15000, 0.04),
    "XX":         (0.0005, 100,   0.04),
}

# Year-over-year weather factor for per-account consumption (shared across
# service areas). 2022-2023 reflect a hot/dry stretch; 2026 is partial
# (Jan-Apr, cooler months, so a lower annual-average GPD).
WEATHER = {2019: 1.00, 2020: 0.98, 2021: 0.97, 2022: 1.09,
           2023: 1.06, 2024: 1.00, 2025: 1.02, 2026: 0.93}

# Fabricated street names for map tooltips (no real premises).
STREETS = [
    "OAK HOLLOW", "PECAN GROVE", "MAGNOLIA", "BLUEBONNET", "CYPRESS BEND",
    "LONGLEAF", "SYCAMORE", "WILLOW BEND", "PRAIRIE VIEW", "MOCKINGBIRD",
    "CARDINAL", "MEADOWBROOK", "STONEBRIDGE", "CLEARWATER", "FOX RUN",
    "HERON LAKE", "PELICAN", "SANDPIPER", "JUNIPER", "REDBUD",
    "DOGWOOD", "HAWTHORNE", "IVYWOOD", "KESTREL", "LARKSPUR",
    "MARIGOLD", "NUTMEG", "OSPREY", "PINTAIL", "QUAIL RIDGE",
    "RIVERBEND", "SADDLEBROOK", "TIMBERLINE", "UPLAND", "VERBENA",
    "WINDMILL", "YAUPON", "ZINNIA", "GRANITE FALLS", "HARVEST MOON",
]


def service_area_center(name):
    """Random-but-plausible center inside a metro-scale bounding box.

    Name keywords nudge the point toward the matching side of the metro so
    the layout looks sane; coordinates correspond to no real premises.
    """
    lat = rng.uniform(29.62, 29.98)
    lon = rng.uniform(-95.62, -95.18)
    if name in ("Kingwood", "Forest Cove", "West Lake Houston"):
        return rng.uniform(30.00, 30.06), rng.uniform(-95.30, -95.15)
    if "North" in name:
        lat = rng.uniform(29.90, 30.05)
    if "South" in name:
        lat = rng.uniform(29.58, 29.70)
    if "West" in name:
        lon = rng.uniform(-95.70, -95.50)
    if "East" in name:
        lon = rng.uniform(-95.25, -95.08)
    return lat, lon


def lognormal(mean, sigma):
    """Lognormal sample whose expected value is roughly `mean`."""
    return mean * math.exp(rng.gauss(0, sigma) - sigma * sigma / 2)


def build():
    agg_rows = []
    chunks = {}       # sa -> list of map points
    all_basins = set()

    for sa in SERVICE_AREAS:
        prefix = BASIN_PREFIX[sa]
        n_basins = rng.randint(4, 6)
        basins = [f"{prefix}{i:03d}" for i in range(1, n_basins + 1)]
        all_basins.update(basins)

        # Overall size of the service area (accounts served).
        sa_accounts = int(lognormal(9000, 0.9))
        sa_accounts = max(800, min(sa_accounts, 60000))
        sa_gpd_factor = rng.uniform(0.85, 1.15)
        growth = rng.uniform(0.997, 1.022)  # annual account growth

        # Split accounts across basins.
        shares = [rng.uniform(0.5, 1.5) for _ in basins]
        total_share = sum(shares)

        for mb, share in zip(basins, shares):
            basin_accounts = sa_accounts * share / total_share
            for ac, (weight, gpd_mean, presence) in CLASSES.items():
                if rng.random() > presence:
                    continue  # class not present in this basin
                base_count = basin_accounts * weight * rng.uniform(0.6, 1.5)
                base_count = max(1, base_count)
                base_gpd = gpd_mean * sa_gpd_factor * rng.uniform(0.8, 1.25)

                for year in YEARS:
                    yrs = year - YEARS[0]
                    count = max(1, round(base_count * growth ** yrs
                                         * rng.uniform(0.97, 1.03)))
                    weather = WEATHER[year]
                    if ac == "IRRIG":  # irrigation is weather-sensitive
                        weather = weather ** 2.5
                    gpd_sum = (count * base_gpd * weather
                               * rng.uniform(0.94, 1.06))
                    agg_rows.append({
                        "YEAR": year,
                        "SERVICE_AR": sa,
                        "METERBASIN": mb,
                        "ACCTCLASS": ac,
                        "gpd_sum": round(gpd_sum, 1),
                        "acct_count": count,
                    })

        # Map chunk: one point per sampled account premise.
        lat0, lon0 = service_area_center(sa)
        n_points = rng.randint(110, 170)
        # Cap RES so other classes stay visible on the map.
        map_weights = {ac: min(w, 0.55) for ac, (w, _, _) in CLASSES.items()}
        classes, weights = zip(*map_weights.items())
        points = []
        for _ in range(n_points):
            ac = rng.choices(classes, weights=weights, k=1)[0]
            gpd_mean = CLASSES[ac][1]  # mean gallons/day for this class
            missing_addr = rng.random() < 0.03
            points.append({
                "sa": sa,
                "mb": rng.choice(basins),
                "ac": ac,
                "lat": round(lat0 + rng.gauss(0, 0.020), 5),
                "lon": round(lon0 + rng.gauss(0, 0.022), 5),
                "gpd_sum": round(max(0.0, lognormal(gpd_mean, 0.7)), 1),
                "addr": "" if missing_addr else str(rng.randint(100, 17999)),
                "st": "" if missing_addr else rng.choice(STREETS),
            })
        chunks[sa] = points

    # Sort DATA_AGG by year, then service area / basin / class.
    agg_rows.sort(key=lambda r: (r["YEAR"], r["SERVICE_AR"],
                                 r["METERBASIN"], r["ACCTCLASS"]))

    meta = {
        "years": YEARS,
        "serviceAreas": sorted(SERVICE_AREAS),
        "meterBasins": sorted(all_basins),
        "acctClasses": sorted(CLASSES),
        "partialYears": PARTIAL_YEARS,
    }
    map_index = {sa: f"data/map/{slug}.js" for sa, slug in SERVICE_AREAS.items()}

    return agg_rows, meta, map_index, chunks


def dumps(obj):
    return json.dumps(obj, separators=(",", ":"), ensure_ascii=False)


def main():
    DATA_DIR.mkdir(exist_ok=True)
    MAP_DIR.mkdir(exist_ok=True)

    agg_rows, meta, map_index, chunks = build()

    data_js = (
        HEADER
        + 'window.DATA_VERSION = "sample-0001";\n'
        + f"window.DATA_META = {dumps(meta)};\n"
        + f"window.DATA_AGG = {dumps(agg_rows)};\n"
        + f"window.DATA_MAP_INDEX = {dumps(map_index)};\n"
    )
    (DATA_DIR / "data.js").write_text(data_js)
    print(f"data/data.js  {len(agg_rows):,} rows  "
          f"{len(data_js) / 1024:.0f} KB")

    total_pts = total_kb = 0
    for sa, slug in SERVICE_AREAS.items():
        body = (
            HEADER
            + "window.DATA_MAP_CHUNKS=window.DATA_MAP_CHUNKS||{};"
            + f'window.DATA_MAP_CHUNKS[{dumps(sa)}]={dumps(chunks[sa])};\n'
        )
        (MAP_DIR / f"{slug}.js").write_text(body)
        total_pts += len(chunks[sa])
        total_kb += len(body) / 1024
    print(f"data/map/*.js  {len(SERVICE_AREAS)} files  "
          f"{total_pts:,} points  {total_kb:.0f} KB total")


if __name__ == "__main__":
    main()
